# Generated by Django 4.1.5 on 2023-01-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
