# Generated by Django 4.1.5 on 2023-01-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_sales', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagge',
            new_name='image',
        ),
    ]
