# Generated by Django 4.1.5 on 2023-01-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_sales', '0003_rename_imagge_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
    ]
